### ISSUE TITLE
Can't use the parser if I have the libraries locally

### ISSUE THREAD

**Issue by cluj-nlp** [allenai/science-parse#100]
I have the project locally and it created the libraries it needed.
When I try to use the Parser I get this error

00:13:12.723 [run-main-4] DEBUG com.amazonaws.metrics.AwsSdkMetrics - Admin mbean registered under com.amazonaws.management:type=AwsSdkMetrics/1
00:13:13.090 [run-main-4] DEBUG c.a.internal.config.InternalConfig - Configuration override awssdk_config_override.json not found.
[error] (run-main-4) java.lang.NoClassDefFoundError: scala/Product$class
[error] java.lang.NoClassDefFoundError: scala/Product$class
[error] 	at org.allenai.datastore.Datastore$Locator.<init>(Datastore.scala:96)
[error] 	at org.allenai.datastore.Datastore.filePath(Datastore.scala:343)
[error] 	at org.allenai.scienceparse.Parser.getDefaultProductionModel(Parser.java:107)
[error] 	at org.allenai.scienceparse.Parser.<init>(Parser.java:127)
[error] 	at org.allenai.scienceparse.Parser.getInstance(Parser.java:122)
[error] 	at ai.lum.paperreader.Test$.main(test.scala:21)
[error] 	at ai.lum.paperreader.Test.main(test.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.Run.invokeMain(Run.scala:89)
[error] 	at sbt.Run.run0(Run.scala:83)
[error] 	at sbt.Run.execute$1(Run.scala:61)
[error] 	at sbt.Run.$anonfun$run$4(Run.scala:73)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:252)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.lang.ClassNotFoundException: scala.Product$class

**Comment by myedibleenso** [comment]
@cluj-nlp, this error is due to a Scala version conflict.  You're using 2.12 in your project, but 2.12 isn't compatible with the 2.11 version of `science-parse`.
