### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by mahmoudaymo** [allenai/science-parse#106]
I have followed the instruction as per cli and I get the folloiwng error and i am not sure why, could you please help me with the issue.

java -Xmx6g -jar science-parse-cli-assembly-1.3.2-SNAPSHOT.jar -o /home/usr/papers/ -f ox.json /home/usr/papers/OX.pdf
00:05:29.631 [main] DEBUG com.amazonaws.AmazonWebServiceClient - Internal logging successfully configured to commons logger: true
00:05:30.001 [main] DEBUG com.amazonaws.metrics.AwsSdkMetrics - Admin mbean registered under com.amazonaws.management:type=AwsSdkMetrics
00:05:30.159 [main] DEBUG c.a.internal.config.InternalConfig - Configuration override awssdk_config_override.json not found.
00:05:31.776 [ForkJoinPool-1-worker-1] INFO  org.allenai.scienceparse.Parser - Loading gazetteer from /home/mahmoud/.ai2/datastore/public/org.allenai.scienceparse/gazetteer-v5.json
00:05:31.777 [ModelLoaderThread] INFO  org.allenai.scienceparse.Parser - Loading model from /home/mahmoud/.ai2/datastore/public/org.allenai.scienceparse/productionModel-v9.dat
00:05:31.781 [ForkJoinPool-1-worker-1] INFO  org.allenai.scienceparse.Parser - Loading bib model from /home/mahmoud/.ai2/datastore/public/org.allenai.scienceparse/productionBibModel-v7.dat
00:05:31.828 [ForkJoinPool-1-worker-1] INFO  org.allenai.scienceparse.Parser - Creating gazetteer cache at /tmp/gazetteer-v5.json-57500763.gazetteerCache.bin
00:05:45.620 [ForkJoinPool-1-worker-1] INFO  o.a.scienceparse.ParserGroundTruth - Read 1609659 papers.
00:14:28.071 [ModelLoaderThread] INFO  org.allenai.datastore.Datastore - Starting to wait on /home/mahmoud/.ai2/datastore/public/org.allenai.scienceparse/Word2VecModel-v1.bin.lock
00:21:09.760 [ForkJoinPool-1-worker-1] INFO  o.a.scienceparse.ExtractReferences - could not load kermit gazetter
Exception in thread "main" java.util.concurrent.TimeoutException: Futures timed out after [15 minutes]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:116)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.result(package.scala:116)
	at org.allenai.scienceparse.RunSP$$anonfun$main$1.apply(RunSP.scala:195)
	at org.allenai.scienceparse.RunSP$$anonfun$main$1.apply(RunSP.scala:83)
	at scala.Option.foreach(Option.scala:257)
	at org.allenai.scienceparse.RunSP$.main(RunSP.scala:83)
	at org.allenai.scienceparse.RunSP.main(RunSP.scala)

**Comment by littlejiao** [comment]
I think it may be an issue about network speed, you can try it more times.

**Comment by mahmoudaymo** [comment]
I have tried all the afternoon and many times, I always get the same error.

**Comment by mahmoudaymo** [comment]
I tried on windows too, but now I get this error:
![sbt](https://user-images.githubusercontent.com/8507454/39756128-a6eadcd2-52c8-11e8-8296-43844102b3cb.png)

**Comment by mahmoudaymo** [comment]
Thank you very much, problem solved by changing timeout in line 195.

**Comment by amandalmia14** [comment]
@mahmoudaymo  Can you please help me for this issue [link](https://github.com/allenai/science-parse/issues/112)
