### ISSUE TITLE
Exception in thread "ModelLoaderThread" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by Riccocez** [allenai/science-parse#107]
I'm trying to run the parser as a library in Java. However, every time I'm trying to get an instance of parser `final Parser parser = Parser.getInstance();` I got an `OutOfMemoryError` even despite changing heap space to 8GB.  Are models bigger than that? What it is that the code is doing when loading tokens like ` backgroundBow: definierende = 2.0` ? Do you have any other suggestion apart from increasing heap space? I'm not completely sure if this will help me to solve this issue. Part of the error I get is:

10:58:53.047 [ModelLoaderThread] DEBUG o.a.scienceparse.ParserLMFeatures - backgroundBow: definierende = 2.0
10:58:58.121 [ModelLoaderThread] DEBUG o.a.scienceparse.ParserLMFeatures - backgroundBow: definierenden = 2.0
Exception in thread "ModelLoaderThread" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.String.<init>(String.java:207)
	at java.lang.String.substring(String.java:1969)
	at ch.qos.logback.classic.pattern.TargetLengthBasedClassNameAbbreviator.abbreviate(TargetLengthBasedClassNameAbbreviator.java:58)

**Comment by Riccocez** [comment]
The way I solved this last issue was by adding the jar file of the common core dependency. There are some dependencies that are not up-to-date. I guess you'll update them soon.

<dependency>
    <groupId>org.allenai.common</groupId>
    <artifactId>common-core_2.11</artifactId>
    <version>1.4.8</version>
</dependency>

**Comment by dirkgr** [comment]
If you manually mess with the dependency jars, you might sometimes get `ClassNotFoundException`. I would not recommend doing that.

8GB of heap should be enough, though more is better. Can you show me what exactly you're running to get that `OutOfMemoryError`? Depending on where you configure the memory settings, and the context in which you're running, memory settings might not apply properly.

**Comment by Riccocez** [comment]
I couldn't find the right dependencies by adding them into the pom file, so I went for this temporary solution while those dependencies are updated eventually.
I tried to run it on IntelliJ, set up the heap size for the compiler, which might not be applying memory settings as desired. I'm getting that `OutOfMemoryError` when running `final Parser parser = Parser.getInstance();` within the main method 

![screen shot 2018-05-09 at 13 42 59](https://user-images.githubusercontent.com/9116707/39812947-e276e842-538e-11e8-85f1-f4750d806089.png)

**Comment by dirkgr** [comment]
The heap size of the compiler does not matter in this case. This is about the heap size during runtime.

Do you have a GitHub repo I could look at, or maybe a small example project that shows the problem?

**Comment by dirkgr** [comment]
What do you run to make this fail?

**Comment by sajastu** [comment]
Having the same issue. Could you get around this issue?
