### ISSUE TITLE
Smaller docker image and memory footprint?

### ISSUE THREAD

**Issue by de-code** [allenai/science-parse#108]
Hi,

Thank you for providing Science Parse and a docker image.
I am currently evaluating it. I was wondering whether there are any plans to reduce the size of the docker image and the memory footprint? Is all of that needed for the extraction?

Thank you

**Comment by dirkgr** [comment]
Most of the space in science-parse is used by the model. It's difficult but not impossible to make that smaller. I don't have any plans myself to do this work, but I would be happy to review a pull request.

The easiest path would be to accept some loss in accuracy, and just try training with smaller vocabulary sets. I bet you can get it to 50% the size and only lose 2-3% accuracy.

Another path would be to take only what you need. If you don't care about references, that's a whole model you don't have to load. This would be a fairly easy change.

**Comment by de-code** [comment]
Okay, thank you for the answer. I thought there may be stuff that's not actually needed. But if it is needed for the model then that's fine. Given that you are now looking at a new model it may not be important in the long run anyway.

**Comment by amandalmia14** [comment]
After running the docker, what command I need to give with the .pdf file in order to get .josn as an output.

**Comment by de-code** [comment]
@amandalmia14 your question doesn't seem to be related to the memory footprint of the docker image. Perhaps it might be better to raise a new issue if you are unsure about how to use the API from the documentation?
