### ISSUE TITLE
Access Docker 

### ISSUE THREAD

**Issue by amandalmia14** [allenai/science-parse#111]
Can anyone provide a documentation on API calling via Docker. 
My docker.bintray.io/s2/scienceparse:1.3.2 is running, but the readme doesn't have enough documentation.

Thanks

**Comment by dirkgr** [comment]
The docker container runs a server on a port. It just runs the [server](https://github.com/allenai/science-parse/tree/master/server). So you can use the same command, except point it at the docker container:

```
curl -v -H "Content-type: application/pdf" --data-binary @paper.pdf "http://localhost/v1"
```

**Comment by amandalmia14** [comment]
Ahh..is works perfectly. 

While running the docker in interactive mode, there is no logs when I run the command "curl -v -H "Content-type: application/pdf" --data-binary @paper.pdf "http://localhost:8080/v1"", although it gives the result. 
 
Thanks a lot.
