### ISSUE TITLE
Non-working links

### ISSUE THREAD

**Issue by colingoldberg** [allenai/science-parse#113]
You have a few non-working links here.

eg. in the sentence: In JSON format, the output looks like this (or like this, if you want sections). The easiest way to get started is to use the output from this server.
'output looks like this' gives ERR_EMPTY_RESPONSE
'this, if you want sections' gives ERR_EMPTY_RESPONSE

on https://github.com/allenai/science-parse/blob/master/server/README.md
'http://scienceparse.allenai.org/v1/498bb0efad6ec15dd09d941fb309aa18d6df9f5f' gives ERR_EMPTY_RESPONSE

It looks like http://scienceparse.allenai.org is generally not available.

Regards

Colin Goldberg

**Comment by amandalmia14** [comment]
@dirkgr Can you please address this issue.

**Comment by dirkgr** [comment]
I'm looking into it.

**Comment by dirkgr** [comment]
It is finally fixed! http://scienceparse.allenai.org/v1/498bb0efad6ec15dd09d941fb309aa18d6df9f5f is back up.

**Comment by amandalmia14** [comment]
Cool Thanks @dirkgr 
But in this [http://scienceparse.allenai.org/v1/](url) it give some sample text. :smile:
