### ISSUE TITLE
Parsing mathematics in pdf

### ISSUE THREAD

**Issue by GohioAC** [allenai/science-parse#120]
Using science-parse to extract text from technical literature does not output the mathematical symbols in a structured manner. It mostly maps them to ASCII symbols.

We are interested in obtaining the mathematical formulas in LaTeX or MathML format and are curious if the science-parse tool is capable of providing the same with minor adjustments? In case it is not that straightforward, are you aware of any other open-source tool for this task?

**Comment by dirkgr** [comment]
Sorry, I'm afraid there is no simple way of making science-parse do this.

I hear there is a new version of [ParsCit](https://github.com/WING-NUS/Neural-ParsCit) that might support that? I am not sure though.

There are some venues that force authors to publish the LaTeX source along with the PDF. Maybe you can get your hands on their corpus.

**Comment by dirkgr** [comment]
Ar, ArXiv has LaTeX sources. You could start with that.

**Comment by GohioAC** [comment]
Thanks for the clarification. I have been working with LaTeX sources from ArXiv for a while now. Will take a look at ParsCit.
