### ISSUE TITLE
build failing

### ISSUE THREAD

**Issue by articuno12** [allenai/science-parse#126]
getting the following error on running sbt cli/assembly
platform used - CentOs
`[error] (*:update) sbt.ResolveException: unresolved dependency: org.allenai.plugins#allenai-sbt-plugins;1.5.2: not found
[error] unresolved dependency: com.eed3si9n#sbt-assembly;0.14.3: not found
[error] unresolved dependency: com.jsuereth#sbt-pgp;1.0.1: not found
`

**Comment by dirkgr** [comment]
It means you are missing a resolver. I am working on a version that does not need the plugins anymore. You can get it here: https://github.com/allenai/science-parse/pull/128

If Maven Central cooperates, I'll make this the official version in the next few minutes.

**Comment by dirkgr** [comment]
Version 2.0.3 is now live. It should solve this problem.

**Comment by amandalmia14** [comment]
@dirkgr I am getting the following error while building the jar,

`[error] D:\AmanDalmia\Workspace\science-parse-master\science-parse-master\core\src\main\java\org\allenai\scienceparse\BibRecord.java:68:1: unmappable character for encoding Cp1252`

`[error] D:\AmanDalmia\Workspace\science-parse-master\science-parse-master\core\src\main\java\org\allenai\scienceparse\BibRecord.java:68:1: unmappable character for encoding Cp1252`

`[error] D:\AmanDalmia\Workspace\science-parse-master\science-parse-master\core\src\main\java\org\allenai\scienceparse\BibRecord.java:68:1: unmappable character for encoding Cp1252`

Building in Windows.

**Comment by dirkgr** [comment]
A closed issue is not really the best way to report bugs, but try setting `javacOptions += "-encoding utf8"` in `build.sbt`.
