### ISSUE TITLE
Windows Docker Issue

### ISSUE THREAD

**Issue by amandalmia14** [allenai/science-parse#127]
Hi, 

@dirkgr 
I am running docker in my windows (Docker version 17.03.1 CE)
An error is occurring when running an the science parser image. 

![docker_error](https://user-images.githubusercontent.com/13628323/49445381-d22dcd80-f7f7-11e8-97cf-e0d7b1bb6577.PNG)

My system has 64 G RAM and having 8 physical processors. Why the image is getting killed?

Thanks

**Comment by dirkgr** [comment]
It's hard to know from afar, but I just started up the image, using exactly your command, and it worked just fine. I would suspect it's a memory problem. I don't run Windows, but in Docker on Mac, I can specify the maximum amount of memory I want Docker to use. Maybe yours is set too low? The dialog looks like this for me:
![screen shot 2018-12-04 at 14 36 54](https://user-images.githubusercontent.com/920638/49477532-127a5500-f7d2-11e8-81e0-1f6da61d046b.png)

**Comment by amandalmia14** [comment]
Yes, I need to configure the daemon about the RAM and CPU and it worked.
Thanks.
