### ISSUE TITLE
How do I change the default port 8080 within the docker container

### ISSUE THREAD

**Issue by Abhijit-2592** [allenai/science-parse#132]
Hi,
How can I change the port of the service inside the docker container from 8080 to something different let's say 8081. I want this feature because there is another container in my docker network that runs in 8080 port thus causing problems for intercommunication

Thanks

**Comment by stuartspotlight** [comment]
Have you tried remapping the port using docker? E.g:
`docker run -p 8081:8080 science-parse`

**Comment by Abhijit-2592** [comment]
@stuartspotlight thanks that's what I did
