### ISSUE TITLE
Error While running sbt cli/assembly

### ISSUE THREAD

**Issue by Saichethan** [allenai/science-parse#148]
science-parse/cli/build.sbt:5: error: not found: value assembly
mainClass in assembly := Some("org.allenai.scienceparse.RunSP")
             ^
[error] Type error in expression

**Comment by ceroth** [comment]
I had the same problem when I ran `stb cli/assembly` from the cli/ directory. Running from the root of the repository worked for me.

**Comment by Saichethan** [comment]
@ceroth  true
but when I'm running from the root of the repo I'm getting following errors
![Screenshot from 2020-04-26 16-26-37](https://user-images.githubusercontent.com/34788026/80421235-c6b1d980-88f9-11ea-888e-a10910c5bbfa.png)

**Comment by kaglowka** [comment]
Hi,
I just had exactly the same problem @Saichethan 
My environment is Ubuntu 20 with default OpenJDK 11.
I used OpenJDK 8 and it worked!

```bash
sudo apt-get install openjdk-8-jdk
```
Select Java version e.g. using the instructions here: https://linuxconfig.org/how-to-install-java-on-ubuntu-18-04-bionic-beaver-linux

It seems to work!

EDIT: It would be nice if Java prerequisites were included in `README`. But still I'm not sure if Java 8 is the optimal version, I guess we'd need the authors to comment on that.

**Comment by Saichethan** [comment]
@kaglowka thank you for your time,
but even after installing openjdk-8-jdk I'm still getting exactly same error

**Comment by kaglowka** [comment]
I'm sorry to hear that. I don't even work with Java usually, so cannot help you much more, I managed to get it working only through a wild guess.
But maybe if you provide more information on your operating system & JDK version & Scala version someone will have an idea.

As a side note, are you sure that `java -version` outputs 8 now?

**Comment by Saichethan** [comment]
@kaglowka  Thanks buddy
Actually my system had both 11 & 8 and it's using 11 
using sudo update-alternatives --config java I solved

solved!!

**Comment by JaniceXiong** [comment]
> @kaglowka Thanks buddy Actually my system had both 11 & 8 and it's using 11 using sudo update-alternatives --config java I solved
> 
> solved!!

Hi! I use the jdk8 but still meet the same error like below. Any idea will be much helpful. Thanks :)
![image](https://user-images.githubusercontent.com/43976565/137164359-18ed95ed-7c55-4083-89f4-c1a7ad651a42.png)
![image](https://user-images.githubusercontent.com/43976565/137164394-ac678356-6a6f-4288-a3ff-f9b3d0f80f02.png)
