### ISSUE TITLE
Font size pt quality

### ISSUE THREAD

**Issue by dcdowney** [allenai/science-parse#8]
Running PDFExtractor on test/resources/P14-1059.pdf:

The font size pt returned by PDFExtractor is the same for both title and authors, but in the PDF source it appears the title is in a noticeably larger font.  Seems likely this is a pdfbox limitation, but can we work around it?

Specifics:

Page 0 Lines 2 and 3 (title lines) have font size 14
Page 0 Line 4 (author) has font size 14 for author names, w/ size 8 for the single token "and"

Font name (ZPNUSQ+NimbusRomNo9L-Medi) is the same for all lines except the "and" .

**Comment by dirkgr** [comment]
We've switched font extraction completely since this issue was filed. I'm closing it.
