### ISSUE TITLE
Headers and Footers appearing in text

### ISSUE THREAD

**Issue by RC-Jay** [allenai/science-parse#95]
I am using the web API to run science parse on a PDF which has headers and footers. The text in the headers and footers is just appearing in between the text itself, making it impossible to remove them using any pattern.

Below is a example of it.

> 3.2. The GUI main window:The flowchart in the main GUI of LS-OPT (LS-OPT Version 5.2 20**CHAPTER 3: Graphical User Interface**The control bar menus are described in Table 3-1.**CHAPTER 3: Graphical User Interface**Summary Report Open the lsopt_report fileWarnings Open the WARNING_MESSAGE fileErrors Open the EXIT_STATUS fileOpens up the working directoryOther fileâ€¦ Option to open any other text fileAdd Sampling Add additional Sampling. The name of the sampling will be used as the name of a subdirectory used for sampling related databases such as Experiments_n.csv

The text in Bold actually belongs in the header. Its just the heading of the chapter. Also page numbers from footers is also making its way into the text. Could somebody solve this problem, so that data from headers and footers is not given in the output.

**Comment by dirkgr** [comment]
I am afraid that's not a level of fix I can just do quickly. Body text extraction is admittedly not very good. We use it mainly to create a search index, which does not care about a few extra tokens. I'm happy to review any pull request you (or anyone) might have to get cleaner output!

Sorry about that!
