### ISSUE TITLE
 Setting value cannot be null: {file:/D:/Tools/science-parse/science-parse-master/}/*:gitCurrentBranch

### ISSUE THREAD

**Issue by littlejiao** [allenai/science-parse#99]
Hi dirkgr,
When I did  "sbt server/assembly", there was some mistakes.
![default](https://user-images.githubusercontent.com/35133062/38066364-3ad33880-333a-11e8-8bcb-cf026586ef9e.PNG)
Could you tell me how to fix this problem?
Thanks!

**Comment by dirkgr** [comment]
Oh, interesting. I think you are building this outside of a git repo, right? That's what causes this?
